### ISSUE TITLE
Node and edge feature aggreation w.r.t connectivity

### ISSUE THREAD

**Issue by zcaicaros** [chaitjo/graph-convnet-tsp#12]
Hi Chaitanya,

Recently I have been studying your paper ''An Efficient Graph Convolutional Network Technique for the Travelling Salesman Problem'', and tried to understand your proposed GCN model. However I have some questions to discuss with you.

In `gcn_layers.py` function `NodeFeatures` and `EdgeFeatures`, I found that the features of nodes and edges are aggregated as in a fully connected graph, i.e., for every node, any other nodes are all its neighbours. I think this is because in TSP context, you set the state as a fully connected graph. Am I correct?

Further more, if in other domains, such as chemistry, where graph is not fully connected, is there any model for aggregation based on connectivity been implemented, i.e. only neighburs of V will be aggregated together?

**Comment by chaitjo** [comment]
Hi @zcajiayin, thank you very much for your interest! Yes, your understanding is exactly correct. 

For other domains, you can actually find an implementation of the same Residual Gated GCN model in our Benchmarking-GNNs repository: https://github.com/graphdeeplearning/benchmarking-gnns. The implementation uses Deep Graph Library and enables you to apply this model to chemistry, social networks, and other domains as long as the input is formatted as a graph. DGL ensures that aggregation is only done for local graph neighbors and not fully-connected.

Hope it helps!

**Comment by zcaicaros** [comment]
Thank you very much for your reply. It is truly a great research work.
