### ISSUE TITLE
a question about data format in google_tsp_reader

### ISSUE THREAD

**Issue by SpringTY** [chaitjo/graph-convnet-tsp#15]
hi,i have a question about data format, grateful for answer
in utils/google_tsp_reader.py  at line: 83
```python
tour_nodes = [int(node) - 1 for node in line[line.index('output') + 1:-1]][:-1]
```
if raw data is ['1', '9', '3', '2', '8', '7', '6', '4', '5', '10']
then we got [0, 8, 2, 1, 7, 6, 5, 3, 4],

i notice that comment "Don't add final connection for tour/cycle"

so do you mean that don't connect for '10' to '1' for the example?

why we drop the node '10'?

**Comment by chaitjo** [comment]
Hi @SpringTY, thank you for your interest -- I do not remember exactly why this was done -- I think its just an artifact of how the repository may have evolved over time. There is probably no reason why we cannot also return the final connection in the tour in the `tour_nodes`. Ultimately, `tour_nodes` is being further used to create the edge labels adjacency matrix with binary 0/1 labels for each edge. 

Feel free to re-open if further clarifications are needed, apologies for my delayed response.
