### ISSUE TITLE
A code issue

### ISSUE THREAD

**Issue by Wastedzz** [chaitjo/graph-convnet-tsp#16]
hi, thanks for your open-source code. I met a bug when I run the beam search code in utilis/beamsearch.py line96:
`self.mask = self.mask.gather(1, perm_mask)`
where 'perm_mask' should be a LongTensor type, but here its type is FloatTensor. It makes severl beam search-based functions fail to use.

**Comment by maoxiaowei97** [comment]
It's true, the beam search implemented here is completely wrong.

> hi, thanks for your open-source code. I met a bug when I run the beam search code in utilis/beamsearch.py line96:
> `self.mask = self.mask.gather(1, perm_mask)`
> where 'perm_mask' should be a LongTensor type, but here its type is FloatTensor. It makes severl beam search-based functions fail to use.

**Comment by maoxiaowei97** [comment]
> It's true, the beam search implemented here is completely wrong.
> 
> > hi, thanks for your open-source code. I met a bug when I run the beam search code in utilis/beamsearch.py line96:
> > `self.mask = self.mask.gather(1, perm_mask)`
> > where 'perm_mask' should be a LongTensor type, but here its type is FloatTensor. It makes severl beam search-based functions fail to use.

 bestScores, bestScoresId = beam_lk.topk(self.beam_size, 1, True, True)
        # Update scores
 self.scores = bestScores
        # Update backpointers
 prev_k = bestScoresId / self.num_nodes
 self.prev_Ks.append(prev_k)
        # Update outputs
  new_nodes = bestScoresId - prev_k * self.num_nodes
  self.next_nodes.append(new_nodes)
  
  It's obvious that "new_nodes" are always 0 at each advance step, so the search gets nothing.

**Comment by chaitjo** [comment]
Hi @Wastedzz @maoxiaowei97, thank you for your interest. I believe you may be using an incorrect version of PyTorch -- the code was tested with a now ancient version 0.4, but PyTorch has undergone several changes since then. For reproducing exactly, you may have to downgrade your PyTorch version.

**Comment by chaitjo** [comment]
Here are some related issues and discussions for reference:
- https://github.com/chaitjo/graph-convnet-tsp/issues/11
- https://github.com/chaitjo/learning-tsp/issues/1#issuecomment-814688655

Maybe one simple thing to try first to get the code to run would be to update backpointers via integer division:
```
# Update backpointers
prev_k = bestScoresId // self.num_nodes
```

**Comment by maoxiaowei97** [comment]
OK, I figured it out. I apologize for my impertinency. Thank you so much.

**Comment by Wastedzz** [comment]
> Here are some related issues and discussions for reference:
> 
>     * [Error in beamsearch.py #11](https://github.com/chaitjo/graph-convnet-tsp/issues/11)
> 
>     * [GNN Encoder learning-tsp#1 (comment)](https://github.com/chaitjo/learning-tsp/issues/1#issuecomment-814688655)
> 
> 
> Maybe one simple thing to try first to get the code to run would be to update backpointers via integer division:
> 
> ```
> # Update backpointers
> prev_k = bestScoresId // self.num_nodes
> ```

you are right, thanks for your reply!

**Comment by maoxiaowei97** [comment]
> Hi @Wastedzz @maoxiaowei97, thank you for your interest. I believe you may be using an incorrect version of PyTorch -- the code was tested with a now ancient version 0.4, but PyTorch has undergone several changes since then. For reproducing exactly, you may have to downgrade your PyTorch version.

You are right. I've figured it out, and it worked. Thank you so much!

**Comment by chaitjo** [comment]
Great, happy to help, no worries.

**Comment by kumarr99** [comment]
perm_mask = perm_mask.type(torch.int64)

just add in this before gather() line to change the datatype to int64
