### ISSUE TITLE
There is an error in backward pass step as the values are not contigous

### ISSUE THREAD

**Issue by rushikeshn11** [chaitjo/graph-convnet-tsp#17]
![Screenshot from 2022-01-25 11-21-58](https://user-images.githubusercontent.com/73983527/150919224-0e9a8e39-6f00-461d-8035-d15d9edc9e61.png)
![Screenshot from 2022-01-25 11-22-05](https://user-images.githubusercontent.com/73983527/150919233-47713a80-2fce-45ec-9cc5-2523a0f88380.png)

**Comment by chaitjo** [comment]
Hi @rushikeshn11, thank you for your interest. What is your python and pytorch version? Are you using cuda?

**Comment by rushikeshn11** [comment]
hi @chaitjo I saw the previous issues raised and could solve the issue and its working . Thanks.

**Comment by chaitjo** [comment]
Great

**Comment by SH2OCN** [comment]
> hi @chaitjo I saw the previous issues raised and could solve the issue and its working . Thanks.

Hi @rushikeshn11 , I'm afraid I met the same issue as you mentioned. Could you please tell me how did you fix it? Downgrade the PyTorch version or something else? Thank you!

**Comment by chaitjo** [comment]
Yes @SH2OCN , this code has not been upgraded to the latest versions of PyTorch.

**Comment by SH2OCN** [comment]
> Yes @SH2OCN , this code has not been upgraded to the latest versions of PyTorch.

Thanks for the reply : ) @chaitjo 
Do you think it's easy to adapt the code to PyTorch 1.x versions, just in order to avoid the error "grad_input must be contiguous"?

**Comment by chaitjo** [comment]
Yes, I believe it should be possible. I just do not have the time to do so as I have moved on to different research projects.

Another good way to get results for a similar Non-autoregressive TSP model may be to look at @wouterkool's excellent DPDP repository: https://github.com/wouterkool/dpdp.

**Comment by SH2OCN** [comment]
> Yes, I believe it should be possible. I just do not have the time to do so as I have moved on to different research projects.
> 
> Another good way to get results for a similar Non-autoregressive TSP model may be to look at @wouterkool's excellent DPDP repository: https://github.com/wouterkool/dpdp.

Thank you Joshi!
