### ISSUE TITLE
RuntimeError when executing "test backward pass" block in main.ipynb

### ISSUE THREAD

**Issue by bluesquinn777** [chaitjo/graph-convnet-tsp#19]
Hi, when I directly run your code in main.ipynb, other parts are correct, but I received "RuntimeError: grad_input must be contiguous"

![image](https://user-images.githubusercontent.com/55047344/161528095-a2bdbc93-dd28-4a3f-a3fc-c77748b081cd.png)

I think this may be caused by `loss_edges` function, where `y = y.permute(0, 3, 1, 2)` which makes `y` not contiguous anymore? Thanks!

**Comment by Zhulu279** [comment]
I had the same problem at runtime.

**Comment by Zhulu279** [comment]
Did you fix this discontiguous problem？

**Comment by chaitjo** [comment]
Thanks for your interest - please make sure that you use the correct versions of Cuda and PyTorch as prescribed in the README.

**Comment by bluesquinn777** [comment]
> Thanks for your interest - please make sure that you use the correct versions of Cuda and PyTorch as prescribed in the README.

> We ran our code on Ubuntu 16.04, using Python 3.6.7, PyTorch 0.4.1 and CUDA 9.0.

Thanks for your reply, I'm using windows, Python 3. CUDA 11.3, PyTorch 1.11.0, which may lead to this problem. Add `.contiguous()` after `permute` in the loss function can solve this problem.

**Comment by Zhulu279** [comment]
I configured it according to the README, and it is running successfully now, thanks to the author.

**Comment by chaitjo** [comment]
Great

**Comment by nnhhoang** [comment]
> .contiguous()

where do i need to add this tks ! @bluesquinn777
