### ISSUE TITLE
Question: Testing the model on TSPLIB example

### ISSUE THREAD

**Issue by saraalemadi** [chaitjo/graph-convnet-tsp#20]
Hi,

Thanks for sharing your code. I was wondering how can I test the trained model on a single example from TSPLIB dataset (file with an extension .tsp rather than .txt).

Thanks

-Sara

**Comment by chaitjo** [comment]
Hi @saraalemadi, thanks for your interest - you will have to create your own readers for files in that format. In the least case, you will need to read the city coordinates from the new files into a torch tensor of shape (num_cities, 2).
