### ISSUE TITLE
I can not install concorde solver on my system.

### ISSUE THREAD

**Issue by no-wings** [chaitjo/graph-convnet-tsp#4]
i use ubount18.04, according to your method ,the erro is :

ERROR: Command errored out with exit status 1:
     command: /home/xiong/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/graph-convnet-tsp/data/pyconcorde/setup.py'"'"'; __file__='"'"'/home/graph-convnet-tsp/data/pyconcorde/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/graph-convnet-tsp/data/pyconcorde/
    Complete output (242 lines):
    running develop
    running egg_info
    writing pyconcorde.egg-info/PKG-INFO
    writing dependency_links to pyconcorde.egg-info/dependency_links.txt
    writing requirements to pyconcorde.egg-info/requires.txt
    writing top-level names to pyconcorde.egg-info/top_level.txt
    reading manifest file 'pyconcorde.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pyconcorde.egg-info/SOURCES.txt'
    running build_ext
    ./concorde/
    ./concorde/Makefile.in
    ./concorde/configure.in
    ./concorde/configure
    ./concorde/aclocal.m4
    ./concorde/config.guess
    ./concorde/config.sub
    ./concorde/install-sh
    ./concorde/BIGGUY/
    ./concorde/BIGGUY/bg_test.c
    ./concorde/BIGGUY/bigguy.c
    ./concorde/BIGGUY/bigguy.tst
    ./concorde/BIGGUY/Makefile.in
    ./concorde/COMBS/
    ./concorde/COMBS/block.c
    ./concorde/COMBS/co_main.c
    ./concorde/COMBS/dngreedy.c
    ./concorde/COMBS/Makefile.in
    ./concorde/CUT/
    ./concorde/CUT/connect.c
    ./concorde/CUT/cut_st.c
    ./concorde/CUT/gomoryhu.c
    ./concorde/CUT/lin_all.c
    ./concorde/CUT/mc_main.c
    ./concorde/CUT/mincut.c
    ./concorde/CUT/segments.c
    ./concorde/CUT/shrink.c
    ./concorde/CUT/Makefile.in
    ./concorde/EDGEGEN/
    ./concorde/EDGEGEN/delaunay.c
    ./concorde/EDGEGEN/edgegen.c
    ./concorde/EDGEGEN/eg_main.c
    ./concorde/EDGEGEN/mlinkern.c
    ./concorde/EDGEGEN/xnear.c
    ./concorde/EDGEGEN/Makefile.in
    ./concorde/FMATCH/
    ./concorde/FMATCH/fmatch.c
    ./concorde/FMATCH/fm_main.c
    ./concorde/FMATCH/Makefile.in
    ./concorde/HELDKARP/
    ./concorde/HELDKARP/heldkarp.c
    ./concorde/HELDKARP/hk_main.c
    ./concorde/HELDKARP/Makefile.in
    ./concorde/INCLUDE/
    ./concorde/INCLUDE/bigguy.h
    ./concorde/INCLUDE/combs.h
    ./concorde/INCLUDE/consec1.h
    ./concorde/INCLUDE/cut.h
    ./concorde/INCLUDE/cuttree.h
    ./concorde/INCLUDE/delaunay.h
    ./concorde/INCLUDE/edgegen.h
    ./concorde/INCLUDE/fmatch.h
    ./concorde/INCLUDE/heldkarp.h
    ./concorde/INCLUDE/kdtree.h
    ./concorde/INCLUDE/linkern.h
    ./concorde/INCLUDE/localcut.h
    ./concorde/INCLUDE/lp.h
    ./concorde/INCLUDE/machdefs.h
    ./concorde/INCLUDE/macrorus.h
    ./concorde/INCLUDE/mlinkern.h
    ./concorde/INCLUDE/necklace.h
    ./concorde/INCLUDE/pq.h
    ./concorde/INCLUDE/pqsets.h
    ./concorde/INCLUDE/tinytsp.h
    ./concorde/INCLUDE/tsp.h
    ./concorde/INCLUDE/util.h
    ./concorde/INCLUDE/verify.h
    ./concorde/INCLUDE/Makefile.common.in
    ./concorde/INCLUDE/config.h.in
    ./concorde/KDTREE/
    ./concorde/KDTREE/kdbuild.c
    ./concorde/KDTREE/kd_main.c
    ./concorde/KDTREE/kdnear.c
    ./concorde/KDTREE/kdspan.c
    ./concorde/KDTREE/kdtwoopt.c
    ./concorde/KDTREE/Makefile.in
    ./concorde/LINKERN/
    ./concorde/LINKERN/flip_two.c
    ./concorde/LINKERN/linkern.c
    ./concorde/LINKERN/linkern_fixed.c
    ./concorde/LINKERN/linkern_path.c
    ./concorde/LINKERN/lk_main.c
    ./concorde/LINKERN/testpath.c
    ./concorde/LINKERN/Makefile.in
    ./concorde/LOCALCUT/
    ./concorde/LOCALCUT/checker.c
    ./concorde/LOCALCUT/chunks.c
    ./concorde/LOCALCUT/first.c
    ./concorde/LOCALCUT/first_main.c
    ./concorde/LOCALCUT/intmat.c
    ./concorde/LOCALCUT/lift.c
    ./concorde/LOCALCUT/localcut.c
    ./concorde/LOCALCUT/loc_main.c
    ./concorde/LOCALCUT/peeler2.c
    ./concorde/LOCALCUT/peeler.c
    ./concorde/LOCALCUT/separate.c
    ./concorde/LOCALCUT/tsporacl.c
    ./concorde/LOCALCUT/Makefile.in
    ./concorde/LP/
    ./concorde/LP/lpcplex4.c
    ./concorde/LP/lpcplex5.c
    ./concorde/LP/lpcplex6.c
    ./concorde/LP/lpcplex8.c
    ./concorde/LP/lpnone.c
    ./concorde/LP/lpqsopt.c
    ./concorde/LP/Makefile.in
    ./concorde/PQ/
    ./concorde/PQ/consec1.c
    ./concorde/PQ/cuttree.c
    ./concorde/PQ/necklace.c
    ./concorde/PQ/pq.c
    ./concorde/PQ/pqtest.c
    ./concorde/PQ/Makefile.in
    ./concorde/TINY/
    ./concorde/TINY/bnbmsp.c
    ./concorde/TINY/tinytsp.c
    ./concorde/TINY/tt_main.c
    ./concorde/TINY/randtsp.awk
    ./concorde/TINY/Makefile.in
    ./concorde/TOOLS/
    ./concorde/TOOLS/edg2len.c
    ./concorde/TOOLS/edgunion.c
    ./concorde/TOOLS/fconvert.c
    ./concorde/TOOLS/junk.c
    ./concorde/TOOLS/killgrun.c
    ./concorde/TOOLS/lkhalone.c
    ./concorde/TOOLS/lkhboss.c
    ./concorde/TOOLS/lkhgrunt.c
    ./concorde/TOOLS/prob2tsp.c
    ./concorde/TOOLS/showres.c
    ./concorde/TOOLS/subby.c
    ./concorde/TOOLS/tdivide.c
    ./concorde/TOOLS/tour2edg.c
    ./concorde/TOOLS/tourchk.c
    ./concorde/TOOLS/tourlen.c
    ./concorde/TOOLS/ttour.c
    ./concorde/TOOLS/Makefile.in
    ./concorde/TSP/
    ./concorde/TSP/bcontrol.c
    ./concorde/TSP/blkcomb.c
    ./concorde/TSP/blossom.c
    ./concorde/TSP/bosstell.c
    ./concorde/TSP/branch.c
    ./concorde/TSP/cliqhash.c
    ./concorde/TSP/cliqwork.c
    ./concorde/TSP/combcliq.c
    ./concorde/TSP/concorde.c
    ./concorde/TSP/control.c
    ./concorde/TSP/cutcall.c
    ./concorde/TSP/cutpool.c
    ./concorde/TSP/cutserv.c
    ./concorde/TSP/ddecker.c
    ./concorde/TSP/domboss.c
    ./concorde/TSP/domgrunt.c
    ./concorde/TSP/domtest.c
    ./concorde/TSP/ex_price.c
    ./concorde/TSP/generate.c
    ./concorde/TSP/growcomb.c
    ./concorde/TSP/poolcat.c
    ./concorde/TSP/prclique.c
    ./concorde/TSP/prob_io.c
    ./concorde/TSP/probserv.c
    ./concorde/TSP/qsparse.c
    ./concorde/TSP/skeleton.c
    ./concorde/TSP/subboss.c
    ./concorde/TSP/subgate.c
    ./concorde/TSP/subgrunt.c
    ./concorde/TSP/teething.c
    ./concorde/TSP/test_tsp.c
    ./concorde/TSP/tighten.c
    ./concorde/TSP/tsp_call.c
    ./concorde/TSP/tsp_lp.c
    ./concorde/TSP/xtour.c
    ./concorde/TSP/Makefile.in
    ./concorde/UTIL/
    ./concorde/UTIL/allocrus.c
    ./concorde/UTIL/bgetopt.c
    ./concorde/UTIL/dheaps_i.c
    ./concorde/UTIL/edgelen.c
    ./concorde/UTIL/edgemap.c
    ./concorde/UTIL/edgeutil.c
    ./concorde/UTIL/eunion.c
    ./concorde/UTIL/fastread.c
    ./concorde/UTIL/genhash.c
    ./concorde/UTIL/getdata.c
    ./concorde/UTIL/priority.c
    ./concorde/UTIL/safe_io.c
    ./concorde/UTIL/signal.c
    ./concorde/UTIL/sortrus.c
    ./concorde/UTIL/subdiv.c
    ./concorde/UTIL/urandom.c
    ./concorde/UTIL/util.c
    ./concorde/UTIL/zeit.c
    ./concorde/UTIL/Makefile.in
    ./concorde/VERIFY/
    ./concorde/VERIFY/verify.c
    ./concorde/VERIFY/ver_main.c
    ./concorde/VERIFY/verlist.tst
    ./concorde/VERIFY/Makefile.in
    ./concorde/README
    loading cache ./config.cache
    checking host system type... configure: error: can not guess host type; you must specify one
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 174, in <module>
        'build_ext': build_ext,
      File "/home/xiong/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/xiong/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/xiong/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/xiong/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xiong/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/xiong/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/xiong/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/xiong/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 115, in run
        build_concorde()
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 99, in build_concorde
        _run(cwd, "build/concorde")
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 76, in _run
        subprocess.check_call(cmd, shell=True, cwd=cwd)
      File "/home/xiong/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'CFLAGS="-fPIC -O2 -g" ./configure --prefix /home/graph-convnet-tsp/data/pyconcorde/data --with-qsopt=/home/graph-convnet-tsp/data/pyconcorde/data ' returned non-zero exit status 1.
    building concorde
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/xiong/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/graph-convnet-tsp/data/pyconcorde/setup.py'"'"'; __file__='"'"'/home/graph-convnet-tsp/data/pyconcorde/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by chaitjo** [comment]
Sorry, I think the issue is related to the python bindings for Concorde, not this codebase.
