### ISSUE TITLE
runerror

### ISSUE THREAD

**Issue by WoNiuHu** [chaitjo/graph-convnet-tsp#6]
![image](https://user-images.githubusercontent.com/18678184/94387697-804cf900-017d-11eb-9fc1-fb32766bfedd.png)
when I try to run this code, but it makes errors like this, how to fix it? I just want to train it in my mac and then test the model. thanks. So how should I change the code for support it run in my macbook

**Comment by chaitjo** [comment]
Hi, thanks for your interest! Can you share more about which Python version, PyTorch, Cuda, etc. version you are using? I have tested the code on Linux 16.04 with the following packages: https://github.com/chaitjo/graph-convnet-tsp/blob/master/requirements.txt

**Comment by WoNiuHu** [comment]
> Hi, thanks for your interest! Can you share more about which Python version, PyTorch, Cuda, etc. version you are using? I have tested the code on Linux 16.04 with the following packages: https://github.com/chaitjo/graph-convnet-tsp/blob/master/requirements.txt

python 3.6.5 
torch 1.6.0
numpy 1.19.2
scipy  1.5.2
matplotlib 3.3.2
tensorflow 2.3.1

I think I didn't have cuda in my macbook.

**Comment by chaitjo** [comment]
You'll need to match package versions, e.g. torch to 0.4. See the above file I shared.

**Comment by WoNiuHu** [comment]
> You'll need to match package versions, e.g. torch to 0.4. See the above file I shared.

thanks, it seems work.

**Comment by chaitjo** [comment]
Great!
